local PANEL = {}
function PANEL:Init()
    self:SetSize(ScrW()-100,ScrH()-50)    
    self:MakePopup()
    self:Center()
    local text = LocalPlayer():GetCharacter():GetData("terminal_licence")
    self:SetTitle(text and "Licence: "..text.." licence" or "")
    self:SetDraggable(false)
    self:ShowCloseButton(false)
    self:SetAlpha(0)
    self:AlphaTo(255, 1, 0)
    local businessmenu = self:Add("ixBusiness")
    self.checkout = businessmenu:Add("DButton")
    self.checkout:Dock(BOTTOM)
    self.checkout:SetTextColor(color_white)
    self.checkout:SetTall(36)
    self.checkout:SetFont("ixMediumFont")
    self.checkout:DockMargin(10, 10, 0, 0)
    self.checkout:SetExpensiveShadow(1, Color(0, 0, 0, 150))
    self.checkout:SetText("Close")
    self.checkout.DoClick = function()
        self:Remove()
    end
    self.licences = businessmenu:Add("DButton")
    self.licences:Dock(BOTTOM)
    self.licences:SetTextColor(color_white)
    self.licences:SetTall(36)
    self.licences:SetFont("ixMediumFont")
    self.licences:DockMargin(10, 10, 0, 0)
    self.licences:SetExpensiveShadow(1, Color(0, 0, 0, 150))
    self.licences:SetText("Licences")
    self.licences.DoClick = function()
        vgui.Create("aw_DermaLicence")
    end
end
vgui.Register("aw_TerminalInterface",PANEL,"DFrame")